services:
  server:
    container_name: payment-form-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=2050
    ports:
      - "2050:2050"
    restart: unless-stopped

  client:
    container_name: payment-form-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
    env_file:
      - ./client/.env
    restart: unless-stopped

networks:
  default:
    driver: bridge
